version: "3.7"

services:
  app:
    image: "home-alarm-notifier:latest"
    build: .
    restart: unless-stopped
    secrets:
      - privateKeyPath
      - clientCertPath
      - caCertPath
    environment:
      - IOT_PRIVATE_KEY_PATH=/run/secrets/privateKeyPath
      - IOT_CLIENT_CERT_PATH=/run/secrets/clientCertPath
      - IOT_CA_CERT_PATH=/run/secrets/caCertPath
      - IOT_CLIENT_ID=${IOT_CLIENT_ID}
      - IOT_HOST=${IOT_HOST}
      - DEVICES=${DEVICES}

secrets:
  privateKeyPath:
    file: creds/private.pem.key
  clientCertPath:
    file: creds/certificate.pem.crt
  caCertPath:
    file: creds/AmazonRootCA1.pem
