name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # checkout a dependent project
    - uses: actions/checkout@v4
      with:
        repository: tstibbs/cloud-core
        path: 'cloud-core' # will resolve to /home/runner/work/home-alarm-notifier/home-alarm-notifier/cloud-core

    # checkout 'this' project
    - uses: actions/checkout@v4
      with:
        path: 'home-alarm-notifier' # will resolve to /home/runner/work/home-alarm-notifier/home-alarm-notifier/home-alarm-notifier


    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # cloud services

    - name: Set up environment
      run: mkdir cdk.tmp
      working-directory: home-alarm-notifier/aws/functions

    - name: Load cloud-core dependencies - utils
      run: npm ci
      working-directory: cloud-core/aws/utils
    - name: Load cloud-core dependencies - edge
      run: npm ci
      working-directory: cloud-core/edge/iot
      
    - run: npm ci
      working-directory: home-alarm-notifier/aws/functions
    - run: npm run testsynth
      working-directory: home-alarm-notifier/aws/functions
    - run: npm run test
      working-directory: home-alarm-notifier/aws/functions
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works

    # edge code

    - run: npm ci
      working-directory: home-alarm-notifier/edge/app
    - run: npm run test
      working-directory: home-alarm-notifier/edge/app
    - name: Set up environment for docker build
      run: mkdir -p deps/cloud-core/edge && cp -r ../../cloud-core/edge/iot deps/cloud-core/edge/iot
      working-directory: home-alarm-notifier/edge
    - run: docker-compose build
      working-directory: home-alarm-notifier/edge
